$primary = rgb(e5c799)
$surface = rgb(161311)
$secondary = rgb(cbaba0)
$error = rgb(cf767c)
$tertiary = rgb(9aa887)
$surface_lowest = rgb(181512)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
