# Homebrew packages
brew "curl"       # Command-line tool for transferring data with URLs (supports HTTP, FTP, etc.)
brew "freetds"    # Open-source implementation of the TDS protocol, connecting to MS SQL and Sybase databases
brew "fzf"        # Command-line fuzzy finder for quickly searching and selecting items from the shell
brew "gcc"        # GNU Compiler Collection for compiling C, C++, and other languages
brew "libtirpc"   # Transport-Independent RPC library for handling remote procedure calls
brew "lsd"        # A modern replacement for the `ls` command with better formatting and icons
brew "neovim"     # A modern, enhanced fork of Vim for efficient text editing
brew "stow"       # Symlink manager for managing dotfiles and directories across projects
brew "tmux"       # Terminal multiplexer for managing multiple terminal sessions in one window
brew "zoxide"     # Fast, smarter `cd` command for quickly navigating the file system
brew "bat"        # Enhanced `cat` command with syntax highlighting, line numbers, and more
brew "zsh"        # Zsh shell for better autocompletion, syntax highlighting, and customization
brew "yazi"       # Blazing fast terminal file manager 
