# Execute your favorite apps at launch
exec-once = waybar
exec-once = swaync
exec-once = hypridle
exec-once = swww-daemon
exec-once = hyprsunset
exec-once = swayosd-server
exec-once = paplay ~/.local/share/sounds/system-startup.wav
exec-once = cliphist daemon
exec-once = wl-paste --watch cliphist store
# exec-once = swww img ~/dotfiles/wallpaper.jpg
# exec-once = hyprpm reload -n
# exec-once = ags run ~/Projects/ags/app.ts
