# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more info
windowrule {
    name = floating-tui
    match:class = TUI.float
    rounding = 20
    float = on
}
# windowrule = match:class TUI.float rounding 20, float on                                          

layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.5, match:namespace waybar

layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0.5, match:namespace rofi
layerrule = animation fade, match:namespace rofi

layerrule = blur on, match:namespace swaync-control-center
layerrule = ignore_alpha 0.5, match:namespace swaync-control-center

layerrule = blur on, match:namespace logout_dialog
layerrule = ignore_alpha 0.5, match:namespace logout_dialog

layerrule = blur on, match:namespace gtk4-layer-shell
layerrule = ignore_alpha 0.5, match:namespace gtk4-layer-shell

# windowrule = no_blur on, match:class floorp
windowrule = opacity false, match:class floorp
