# See https://wiki.hyprland.org/Configuring/Variables/ for more


# ----------------------------------------------------- 
# General window layout and colors
# ----------------------------------------------------- 
general {
    gaps_in = 2
    gaps_out = 5
    border_size = 1
    layout = master
    resize_on_border = true
    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    # col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    # col.inactive_border = rgba(595959aa)
}

# dwindle {
#     single_window_aspect_ratio = 4 3
# }


