# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more info
layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.5, match:namespace waybar

layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0.5, match:namespace rofi
layerrule = animation fade, match:namespace rofi

layerrule = blur on, match:namespace swaync-control-center
layerrule = ignore_alpha 0.5, match:namespace swaync-control-center

layerrule = blur on, match:namespace logout_dialog
layerrule = ignore_alpha 0.5, match:namespace logout_dialog
