# See https://wiki.hyprland.org/Configuring/Variables/ for more


# ----------------------------------------------------- 
# General window layout and colors
# ----------------------------------------------------- 
general {
    gaps_in = 2
    gaps_out = 5
    border_size = 1
    layout = master
    resize_on_border = true
    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    # col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    # col.inactive_border = rgba(595959aa)
}


dwindle {
    # tile floating windows
    pseudotile = true

    # split right side only
    force_split = 2

    # don't change splits on resize
    preserve_split = true
}

master {
    # master-slave ratio
    mfact = 0.65
}

