# See https://wiki.hyprland.org/Configuring/Monitors/

# Change to 1 if on a 1x display (then change last "auto" to 1 in monitor=)
# Change to something like 1.75 for fractional scaling (can work well with 1.66667 monitor scaling)
# env = GDK_SCALE,1

# Use single default monitor (see all monitors with: hyprctl monitors)
# Format: monitor = [port], resolution, position, scale
monitor=,preferred,auto,auto
monitor=eDP-1,2880x1800@120.0,4480x0,1.5,mirror,DP-1  #HP OMEN
monitor=DP-1,2560x1080@59.98,1920x0,1.0               #LG Ultrawide

# Exmaple for fractional scaling that works well with GDK_SCALE,1.75
# monitor=,preferred,auto,1.666667

# Example for Framework 13 w/ 6K XDR Apple display
# monitor = DP-5, 6016x3384@60.00, auto, 2
# monitor = eDP-1, 2880x1920@120.00, auto, 2
